# Site settings
title: Blog | Philipp Rieber
email: p.rieber@gmail.com
description: "Philipp Rieber's blog"
baseurl: ""
url: "http://blog.philipp-rieber.net"
twitter_username: bicpi
github_username:  bicpi
paginate: 5
paginate_path: "/page/:num/"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
