# Site settings
title: Blog | Philipp Rieber
email: p.rieber@gmail.com
description: "Philipp Rieber's blog"
baseurl: ""
url: "http://blog.philipp-rieber.net"
twitter_username: bicpi
github_username:  bicpi
paginate: 5
paginate_path: "/page/:num/"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments

email: <script type="text/javascript">ylgjjeeo="i68i65i6Ci6Ci6Fi40i70i68i69i6ci69i70i70i2di72i69i65i62i65i72i2ei6ei65i74";document.write(decodeURIComponent(ylgjjeeo.replace(/i/g, "%")));</script>
